version: "3.8"

services:
    app:
        build: .
        ports:
            - "5111:5111"
        depends_on:
            - redis
        environment:
            - NODE_ENV=development
            - SERVICE_NAME=school_management
            - USER_PORT=5111
            - REDIS_URI=redis://redis:6379  # Use 'redis' as the hostname
            - LONG_TOKEN_SECRET=your_long_token_secret
            - SHORT_TOKEN_SECRET=your_short_token_secret
            - NACL_SECRET=your_nacl_secret
            - OYSTER_REDIS=redis://redis:6379  # Use 'redis' as the hostname
            - OYSTER_PREFIX=school_
        networks:
            - myNetwork
        links:
            - redis

    redis:
        image: redis/redis-stack-server:latest
        container_name: redis
        ports:
            - "6379:6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        command: redis-server --save 20 1 --loglevel warning --protected-mode no
        volumes:
            - cache:/data/redis
        networks:
            - myNetwork

volumes:
    cache:
        driver: local

networks:
    myNetwork:
        driver: bridge